spring.application.name=jobboard
server.port=8080
spring.profiles.active=dev
spring.jackson.property-naming-strattegy=SNAKE_CASE
spring.flyway.locations=classpath:/db/migrations
spring.flyway.schemas=job_board
spring.flyway.baselineOnMigrate=true
spring.flyway.enabled=true
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=editMePlease
spring.datasource.username=user
spring.datasource.password=passwd